// GENERATED by scripts/gen_pending_order_mirror.py from include/pineforge/engine.hpp -- do not edit.
// 68 PendingOrder members mirrored (406 POD fields incl. struct_version/size).
#pragma once
#include <stdint.h>

/* C-compatible value snapshot of one resting pineforge::PendingOrder
 * (spec 3.6). struct_version identifies the field set (this file:
 * 1); size is sizeof(pf_pending_order_v1_t) as the producer
 * compiled it. Strings are copied into a NUL-terminated char[64]
 * (name_truncated = 1 when the source was longer than 63 bytes) with
 * name_hash64 = FNV-1a 64 of the FULL source string. Enums are their
 * int32 value; bool is 0/1 in a uint8_t. Append-only, like every
 * pineforge.h POD. */
typedef struct pf_pending_order_v1_s {
    uint32_t struct_version;
    uint32_t size;
    char id[64];
    uint8_t id_truncated;
    uint64_t id_hash64;
    char from_entry[64];
    uint8_t from_entry_truncated;
    uint64_t from_entry_hash64;
    int32_t type;
    uint8_t is_long;
    double limit_price;  // deprecated, derived output only
    double stop_price;  // deprecated, derived output only
    double trail_points;  // deprecated, derived output only
    double trail_price;  // deprecated, derived output only
    double trail_offset;  // deprecated, derived output only
    double profit_ticks;  // deprecated, derived output only
    double loss_ticks;  // deprecated, derived output only
    double qty;
    int32_t qty_type;
    double qty_percent;
    char oca_name[64];
    uint8_t oca_name_truncated;
    uint64_t oca_name_hash64;
    int32_t oca_type;
    int32_t created_bar;
    int64_t created_seq;
    uint64_t incarnation;
    uint8_t created_by_same_id_replacement;  // deprecated, derived output only
    uint64_t replaced_default_market_incarnation;
    uint8_t declined_by_replaced_short_market;  // deprecated, derived output only
    uint64_t replaced_exit_order_incarnation;  // deprecated, derived output only
    uint64_t recreated_after_named_cancelled_entry_incarnation;
    uint64_t named_cancel_surviving_exit_incarnation;
    uint8_t stop_limit_activated;
    uint8_t coof_suppress_stop_on_entry_bar;  // deprecated, derived output only
    uint8_t coof_suppress_limit_on_entry_bar;  // deprecated, derived output only
    uint8_t created_during_coof_recalc;  // deprecated, derived output only
    uint8_t coof_born_at_close_recalc;  // deprecated, derived output only
    uint8_t coof_born_mid_bar;  // deprecated, derived output only
    int32_t coof_cascade_seg_i;
    uint8_t coof_cascade_inflight_fires;
    int32_t created_position_side;
    int64_t created_position_cycle_seq;
    uint8_t created_after_position_close_in_bar;
    uint8_t over_pyramiding_cap_at_placement;
    int32_t same_id_stop_deferred_close_all_bar;
    uint64_t same_id_stop_deferred_close_all_incarnation;
    uint8_t reverses_same_bar_market_from_flat;
    uint8_t paired_flat_market_candidate;  // deprecated, derived output only
    double paired_flat_market_own_qty;
    double paired_flat_market_signal_close;
    double paired_flat_market_signal_equity;
    double paired_flat_market_signal_margin_pct;
    double paired_flat_market_signal_pointvalue;
    double paired_flat_market_signal_fx;
    int64_t paired_flat_market_peer_seq;
    double paired_flat_market_transaction_qty;
    uint8_t default_flat_market_gross_candidate;  // deprecated, derived output only
    double tv_carry_qty;
    double frozen_default_qty;
    double default_stop_placement_qty;
    double default_stop_placement_equity;
    double default_stop_placement_signal_close;
    double default_stop_sizing_price;
    double sizing_equity;
    double sizing_price;
    double sizing_fx;
    double sizing_mark;
    uint8_t opening_affordability_exemption_candidate;  // deprecated, derived output only
    uint8_t explicit_flat_admission_candidate;  // deprecated, derived output only
    double explicit_placement_equity;
    double explicit_slipped_signal_close;
    double affordability_placement_equity;
    double affordability_signal_price;
    double affordability_held_qty;
    uint8_t affordability_close_only;
    uint8_t rounded_signal_cost_close_only;
    int32_t signal_close_mc_bar;
    uint64_t signal_close_mc_entry_incarnation;
    uint64_t signal_close_mc_fill_seq;
    double signal_close_mc_remaining_qty;
    char comment[64];
    uint8_t comment_truncated;
    uint64_t comment_hash64;
    uint8_t requested_partial;  // deprecated, derived output only
    uint8_t full_percent_exit_request;  // deprecated, derived output only
    uint8_t pooc_global_full_exit_dynamic_qty;  // deprecated, derived output only
    uint8_t pooc_global_full_exit_tracks_bound_adds;  // deprecated, derived output only
    uint8_t pooc_global_full_exit_bound_add;  // deprecated, derived output only
    uint8_t created_while_in_position;  // deprecated, derived output only
    uint8_t sbmt_member;  // deprecated, derived output only
    double sbmt_own_qty;  // deprecated, derived output only
    double sbmt_tx_qty;  // deprecated, derived output only
    uint8_t sbmt_kept_over_cap;  // deprecated, derived output only
    double sbmt_close_qty;  // deprecated, derived output only
    uint8_t sbmt_close_buy;  // deprecated, derived output only
    uint8_t suppress_as_declined_reversal_close;  // deprecated, derived output only
    uint8_t dormant_bracket;  // deprecated, derived output only
    uint8_t dormant_reissue_pending;  // deprecated, derived output only
    double dormant_original_stop_price;  // deprecated, derived output only
    int32_t dormant_hold_bar;  // deprecated, derived output only
    int32_t dormant_reversal_kill_bar;  // deprecated, derived output only
    double dormant_trail_best;  // deprecated, derived output only
    double dormant_trail_best_start;  // deprecated, derived output only
    uint8_t dormant_trail_leg_dead;  // deprecated, derived output only
    double suppressed_close_consumed_ledger_qty;  // deprecated, derived output only
    double suppressed_close_retired_ledger_qty;  // deprecated, derived output only
    int32_t short_seed_collision_role;
    uint64_t replaced_order_incarnation;
    int64_t birth_timestamp;
    int32_t birth_cause;
    int32_t birth_bar;
    int32_t birth_cursor_domain;
    int32_t birth_cursor_position;
    int32_t birth_cursor_index;
    int32_t birth_cursor_count;
    double birth_cursor_price;
    uint64_t birth_first_fill;
    uint64_t birth_last_fill;
    uint64_t birth_evaluation_ordinal;
    int32_t pine_birth_reach;
    uint64_t quantity_intent_kind;
    double quantity_intent_units;
    double quantity_intent_numerator;
    double quantity_intent_denominator;
    uint8_t quantity_reservation_present;
    double quantity_reservation_units;
    double quantity_reservation_basis_units;
    int64_t leg_activation_owner_cycle;
    uint8_t leg_activation_present;
    int64_t leg_activation_stop_first_bar;
    int64_t leg_activation_limit_first_bar;
    int64_t pine_exit_activation_owner_cycle_at_birth;
    uint8_t pine_exit_activation_present;
    int32_t pine_exit_activation_entry_bar_at_birth;
    int32_t pine_exit_activation_direction_at_birth;
    double pine_exit_activation_cursor_price_at_birth;
    double pine_exit_activation_stop_level_at_birth;
    double pine_exit_activation_limit_level_at_birth;
    uint8_t pine_exit_activation_limit_continuation_present;
    int32_t pine_exit_activation_limit_continuation_cause;
    uint64_t pine_exit_activation_limit_continuation_fill;
    int64_t reservation_expansion_position_cycle;
    uint8_t reservation_expansion_present;
    int32_t reservation_expansion_side;
    uint8_t reservation_expansion_first_later_admission_present;
    uint64_t reservation_expansion_first_later_admission;
    uint8_t reservation_growth_source_present;
    uint64_t reservation_growth_source_reservation_owner;
    uint64_t pine_frozen_market_instruction_kind;
    double pine_frozen_market_instruction_own_units;
    double pine_frozen_market_instruction_transaction_units;
    char pine_frozen_market_instruction_target_id[64];
    uint8_t pine_frozen_market_instruction_target_id_truncated;
    uint64_t pine_frozen_market_instruction_target_id_hash64;
    uint64_t legs_target_incarnation;
    int64_t legs_target_owner;
    uint64_t legs_revision;
    uint64_t legs_definition_incarnation;
    uint64_t legs_definition_revision;
    uint8_t legs_definition_value_present;
    double legs_definition_limit_price;
    double legs_definition_stop_price;
    double legs_definition_trail_points;
    double legs_definition_trail_price;
    double legs_definition_trail_offset;
    double legs_definition_profit_ticks;
    double legs_definition_loss_ticks;
    uint64_t legs_generation0;
    uint8_t legs_retirement0_present;
    uint64_t legs_retirement0_generation;
    uint64_t legs_retirement0_cause_event;
    int64_t legs_retirement0_cause_bar;
    uint32_t legs_retirement0_cause_domain;
    uint32_t legs_retirement0_cause_phase;
    uint64_t legs_generation1;
    uint8_t legs_retirement1_present;
    uint64_t legs_retirement1_generation;
    uint64_t legs_retirement1_cause_event;
    int64_t legs_retirement1_cause_bar;
    uint32_t legs_retirement1_cause_domain;
    uint32_t legs_retirement1_cause_phase;
    uint64_t legs_generation2;
    uint8_t legs_retirement2_present;
    uint64_t legs_retirement2_generation;
    uint64_t legs_retirement2_cause_event;
    int64_t legs_retirement2_cause_bar;
    uint32_t legs_retirement2_cause_domain;
    uint32_t legs_retirement2_cause_phase;
    uint8_t legs_suspension_present;
    uint64_t legs_suspension_cause_event;
    int64_t legs_suspension_cause_bar;
    uint32_t legs_suspension_cause_domain;
    uint32_t legs_suspension_cause_phase;
    uint32_t legs_suspension_legs_count;
    uint32_t legs_suspension_legs_item0;
    uint32_t legs_suspension_legs_item1;
    uint32_t legs_suspension_legs_item2;
    uint8_t legs_suspension_hold_present;
    uint64_t legs_suspension_hold_requested_event;
    int64_t legs_suspension_hold_requested_bar;
    uint32_t legs_suspension_hold_requested_domain;
    uint32_t legs_suspension_hold_requested_phase;
    uint64_t legs_suspension_hold_target_incarnation;
    int64_t legs_suspension_hold_target_owner;
    uint64_t legs_suspension_hold_revision;
    uint8_t legs_suspension_revival_definition_present;
    uint64_t legs_suspension_revival_definition_incarnation;
    uint64_t legs_suspension_revival_definition_revision;
    uint8_t legs_suspension_revival_definition_value_present;
    double legs_suspension_revival_definition_limit_price;
    double legs_suspension_revival_definition_stop_price;
    double legs_suspension_revival_definition_trail_points;
    double legs_suspension_revival_definition_trail_price;
    double legs_suspension_revival_definition_trail_offset;
    double legs_suspension_revival_definition_profit_ticks;
    double legs_suspension_revival_definition_loss_ticks;
    uint8_t legs_suspension_replacement_present;
    uint64_t legs_suspension_replacement_queue_predecessor;
    uint64_t legs_suspension_replacement_revival_definition_incarnation;
    uint64_t legs_suspension_replacement_revival_definition_revision;
    uint8_t legs_suspension_replacement_revival_definition_value_present;
    double legs_suspension_replacement_revival_definition_limit_price;
    double legs_suspension_replacement_revival_definition_stop_price;
    double legs_suspension_replacement_revival_definition_trail_points;
    double legs_suspension_replacement_revival_definition_trail_price;
    double legs_suspension_replacement_revival_definition_trail_offset;
    double legs_suspension_replacement_revival_definition_profit_ticks;
    double legs_suspension_replacement_revival_definition_loss_ticks;
    uint64_t legs_suspension_replacement_release_requested_event;
    int64_t legs_suspension_replacement_release_requested_bar;
    uint32_t legs_suspension_replacement_release_requested_domain;
    uint32_t legs_suspension_replacement_release_requested_phase;
    uint64_t legs_suspension_replacement_release_target_incarnation;
    int64_t legs_suspension_replacement_release_target_owner;
    uint64_t legs_suspension_replacement_release_revision;
    uint8_t legs_suspension_window_present;
    uint64_t legs_suspension_window_excluded_event;
    int64_t legs_suspension_window_excluded_bar;
    uint32_t legs_suspension_window_excluded_domain;
    uint32_t legs_suspension_window_excluded_phase;
    double legs_suspension_window_best;
    double legs_suspension_window_prefix;
    uint8_t legs_last_present;
    uint64_t legs_last_target_incarnation;
    int64_t legs_last_target_owner;
    uint64_t legs_last_expected_revision;
    uint64_t legs_last_cause_event;
    int64_t legs_last_cause_bar;
    uint32_t legs_last_cause_domain;
    uint32_t legs_last_cause_phase;
    uint32_t legs_last_operation;
    int64_t legs_last_bind_owner;
    uint32_t legs_last_suspend_legs_count;
    uint32_t legs_last_suspend_legs_item0;
    uint32_t legs_last_suspend_legs_item1;
    uint32_t legs_last_suspend_legs_item2;
    uint8_t legs_last_suspend_hold_present;
    uint64_t legs_last_suspend_hold_requested_event;
    int64_t legs_last_suspend_hold_requested_bar;
    uint32_t legs_last_suspend_hold_requested_domain;
    uint32_t legs_last_suspend_hold_requested_phase;
    uint64_t legs_last_suspend_hold_target_incarnation;
    int64_t legs_last_suspend_hold_target_owner;
    uint64_t legs_last_suspend_hold_revision;
    uint8_t legs_last_suspend_window_present;
    uint64_t legs_last_suspend_window_excluded_event;
    int64_t legs_last_suspend_window_excluded_bar;
    uint32_t legs_last_suspend_window_excluded_domain;
    uint32_t legs_last_suspend_window_excluded_phase;
    double legs_last_suspend_window_best;
    double legs_last_suspend_window_prefix;
    uint32_t legs_last_suspend_retire_count;
    uint32_t legs_last_suspend_retire_item0;
    uint32_t legs_last_suspend_retire_item1;
    uint32_t legs_last_suspend_retire_item2;
    uint64_t legs_last_stage_queue_predecessor;
    uint64_t legs_last_stage_revival_definition_incarnation;
    uint64_t legs_last_stage_revival_definition_revision;
    uint8_t legs_last_stage_revival_definition_value_present;
    double legs_last_stage_revival_definition_limit_price;
    double legs_last_stage_revival_definition_stop_price;
    double legs_last_stage_revival_definition_trail_points;
    double legs_last_stage_revival_definition_trail_price;
    double legs_last_stage_revival_definition_trail_offset;
    double legs_last_stage_revival_definition_profit_ticks;
    double legs_last_stage_revival_definition_loss_ticks;
    uint64_t legs_last_stage_release_requested_event;
    int64_t legs_last_stage_release_requested_bar;
    uint32_t legs_last_stage_release_requested_domain;
    uint32_t legs_last_stage_release_requested_phase;
    uint64_t legs_last_stage_release_target_incarnation;
    int64_t legs_last_stage_release_target_owner;
    uint64_t legs_last_stage_release_revision;
    uint32_t legs_last_restore_legs_count;
    uint32_t legs_last_restore_legs_item0;
    uint32_t legs_last_restore_legs_item1;
    uint32_t legs_last_restore_legs_item2;
    uint64_t legs_last_complete_completed_event;
    int64_t legs_last_complete_completed_bar;
    uint32_t legs_last_complete_completed_domain;
    uint32_t legs_last_complete_completed_phase;
    uint8_t legs_last_complete_requested_present;
    uint64_t legs_last_complete_requested_requested_event;
    int64_t legs_last_complete_requested_requested_bar;
    uint32_t legs_last_complete_requested_requested_domain;
    uint32_t legs_last_complete_requested_requested_phase;
    uint64_t legs_last_complete_requested_target_incarnation;
    int64_t legs_last_complete_requested_target_owner;
    uint64_t legs_last_complete_requested_revision;
    double legs_last_observe_high;
    double legs_last_observe_low;
    int32_t legs_last_observe_direction;
    uint32_t legs_last_observe_fold;
    uint32_t legs_last_cancel_legs_count;
    uint32_t legs_last_cancel_legs_item0;
    uint32_t legs_last_cancel_legs_item1;
    uint32_t legs_last_cancel_legs_item2;
    uint64_t market_admission_observation_present;
    uint64_t market_admission_observation_command;
    int64_t market_admission_observation_kind;
    int64_t market_admission_observation_birth_cause;
    int64_t market_admission_observation_birth_bar;
    int64_t market_admission_observation_birth_timestamp;
    int64_t market_admission_observation_birth_cursor_domain;
    int64_t market_admission_observation_birth_cursor_position;
    int64_t market_admission_observation_birth_cursor_index;
    int64_t market_admission_observation_birth_cursor_count;
    double market_admission_observation_birth_cursor_price;
    uint64_t market_admission_observation_birth_first_fill;
    uint64_t market_admission_observation_birth_last_fill;
    uint64_t market_admission_observation_birth_evaluation_ordinal;
    char market_admission_observation_id[64];
    uint8_t market_admission_observation_id_truncated;
    uint64_t market_admission_observation_id_hash64;
    double market_admission_observation_requested_quantity;
    int64_t market_admission_observation_quantity_type;
    uint64_t market_admission_observation_buy;
    double market_admission_observation_prices_limit;
    double market_admission_observation_prices_stop;
    char market_admission_observation_oca_name[64];
    uint8_t market_admission_observation_oca_name_truncated;
    uint64_t market_admission_observation_oca_name_hash64;
    int64_t market_admission_observation_oca_type;
    uint64_t market_admission_observation_configuration_process_on_close;
    uint64_t market_admission_observation_configuration_calc_on_fills;
    uint64_t market_admission_observation_configuration_magnifier;
    uint64_t market_admission_observation_configuration_fill_recalculation;
    uint64_t market_admission_observation_configuration_scheduler;
    int64_t market_admission_observation_configuration_slippage;
    int64_t market_admission_observation_configuration_pyramiding;
    int64_t market_admission_observation_configuration_default_quantity_type;
    double market_admission_observation_configuration_default_quantity_value;
    double market_admission_observation_configuration_long_margin;
    double market_admission_observation_configuration_short_margin;
    double market_admission_observation_configuration_commission_value;
    int64_t market_admission_observation_configuration_commission_type;
    double market_admission_observation_configuration_pointvalue;
    double market_admission_observation_configuration_fx;
    double market_admission_observation_configuration_quantity_step;
    double market_admission_observation_configuration_mintick;
    int64_t market_admission_observation_configuration_risk_direction;
    int64_t market_admission_observation_configuration_loss_days_limit;
    double market_admission_observation_configuration_drawdown_limit;
    double market_admission_observation_configuration_intraday_loss_limit;
    double market_admission_observation_configuration_position_limit;
    uint64_t market_admission_observation_configuration_fill_cap_active;
    uint64_t market_admission_observation_configuration_risk_halted;
    int64_t market_admission_observation_bar;
    int64_t market_admission_observation_placement_side;
    int64_t market_admission_observation_placement_cycle;
    double market_admission_observation_prior_close_quantity;
    double market_admission_observation_held_quantity;
    int64_t market_admission_observation_held_entries;
    double market_admission_observation_realized_equity;
    double market_admission_observation_placement_equity;
    double market_admission_observation_signal_close;
    double market_admission_observation_quantized_fixed_quantity;
    uint64_t market_admission_observation_original_sizing_present;
    double market_admission_observation_original_sizing_quantity;
    double market_admission_observation_original_sizing_equity;
    double market_admission_observation_original_sizing_price;
    double market_admission_observation_original_sizing_mark;
    double market_admission_observation_original_sizing_fx;
    double market_admission_observation_explicit_equity;
    double market_admission_observation_explicit_price;
    uint64_t market_admission_review_present;
    uint64_t market_admission_review_sequence;
    int64_t market_admission_review_checkpoint;
    int64_t market_admission_review_bar;
    uint64_t market_admission_sizing_revision_present;
    uint64_t market_admission_sizing_revision_sequence;
    uint64_t market_admission_sizing_revision_cause_fill;
    int64_t market_admission_sizing_revision_bar;
    uint64_t market_admission_review_target_command;
    uint64_t market_admission_sizing_revision_target_command;
    int32_t cancellation_cause;
    int32_t cancellation_state;
    int32_t cancellation_close_claim_release;
    uint64_t cancellation_source_incarnation;
    int64_t cancellation_source_sequence;
    uint64_t cancellation_target_incarnation;
    int64_t cancellation_target_owner;
    uint64_t cancellation_target_revision;
    double cancellation_close_claim_consumed;
    double cancellation_close_claim_retired;
} pf_pending_order_v1_t;

/* One row of the self-describing layout table returned by
 * strategy_pending_order_layout(): field name, C type spelling
 * ("uint8_t", "int32_t", "int64_t", "uint64_t", "double", "char[64]",
 * "uint32_t"), byte offset inside pf_pending_order_v1_t, byte size. */
typedef struct pf_field_desc_s {
    const char* name;
    const char* type;
    uint32_t offset;
    uint32_t size;
} pf_field_desc_t;
#define PF_PENDING_ORDER_STRUCT_VERSION 1
#define PF_PENDING_ORDER_FIELD_COUNT 406
#define PF_PENDING_ORDER_STR_CAP 64
