// GENERATED by scripts/gen_pending_order_mirror.py from include/pineforge/engine.hpp -- do not edit.
// 74 PendingOrder members mirrored (155 POD fields incl. struct_version/size).
#pragma once
#include <stdint.h>

/* C-compatible value snapshot of one resting pineforge::PendingOrder
 * (spec 3.6). struct_version identifies the field set (this file:
 * 1); size is sizeof(pf_pending_order_v1_t) as the producer
 * compiled it. Strings are copied into a NUL-terminated char[64]
 * (name_truncated = 1 when the source was longer than 63 bytes) with
 * name_hash64 = FNV-1a 64 of the FULL source string. Enums are their
 * int32 value; bool is 0/1 in a uint8_t. Append-only, like every
 * pineforge.h POD. */
typedef struct pf_pending_order_v1_s {
    uint32_t struct_version;
    uint32_t size;
    char id[64];
    uint8_t id_truncated;
    uint64_t id_hash64;
    char from_entry[64];
    uint8_t from_entry_truncated;
    uint64_t from_entry_hash64;
    int32_t type;
    uint8_t is_long;
    double limit_price;  // deprecated, derived output only
    double stop_price;  // deprecated, derived output only
    double trail_points;  // deprecated, derived output only
    double trail_price;  // deprecated, derived output only
    double trail_offset;  // deprecated, derived output only
    double profit_ticks;  // deprecated, derived output only
    double loss_ticks;  // deprecated, derived output only
    double qty;
    int32_t qty_type;
    double qty_percent;
    char oca_name[64];
    uint8_t oca_name_truncated;
    uint64_t oca_name_hash64;
    int32_t oca_type;
    int32_t created_bar;
    int64_t created_seq;
    uint64_t incarnation;
    uint8_t created_by_same_id_replacement;  // deprecated, derived output only
    uint64_t replaced_default_market_incarnation;
    uint8_t declined_by_replaced_short_market;
    uint64_t replaced_exit_order_incarnation;  // deprecated, derived output only
    uint64_t recreated_after_named_cancelled_entry_incarnation;
    uint64_t named_cancel_surviving_exit_incarnation;
    uint8_t stop_limit_activated;
    uint8_t coof_suppress_stop_on_entry_bar;  // deprecated, derived output only
    uint8_t coof_suppress_limit_on_entry_bar;  // deprecated, derived output only
    uint8_t created_during_coof_recalc;  // deprecated, derived output only
    uint8_t coof_born_at_close_recalc;  // deprecated, derived output only
    uint8_t coof_born_mid_bar;  // deprecated, derived output only
    int32_t coof_cascade_seg_i;
    uint8_t coof_cascade_inflight_fires;
    int32_t created_position_side;
    int64_t created_position_cycle_seq;
    uint8_t created_after_position_close_in_bar;
    uint8_t over_pyramiding_cap_at_placement;
    int32_t same_id_stop_deferred_close_all_bar;
    uint64_t same_id_stop_deferred_close_all_incarnation;
    uint8_t reverses_same_bar_market_from_flat;
    uint8_t paired_flat_market_candidate;
    double paired_flat_market_own_qty;
    double paired_flat_market_signal_close;
    double paired_flat_market_signal_equity;
    double paired_flat_market_signal_margin_pct;
    double paired_flat_market_signal_pointvalue;
    double paired_flat_market_signal_fx;
    int64_t paired_flat_market_peer_seq;
    double paired_flat_market_transaction_qty;
    uint8_t default_flat_market_gross_candidate;
    double tv_carry_qty;
    double frozen_default_qty;
    double default_stop_placement_qty;
    double default_stop_placement_equity;
    double default_stop_placement_signal_close;
    double default_stop_sizing_price;
    double sizing_equity;
    double sizing_price;
    double sizing_fx;
    double sizing_mark;
    uint8_t opening_affordability_exemption_candidate;
    uint8_t explicit_flat_admission_candidate;
    double explicit_placement_equity;
    double explicit_slipped_signal_close;
    double affordability_placement_equity;
    double affordability_signal_price;
    double affordability_held_qty;
    uint8_t affordability_close_only;
    uint8_t rounded_signal_cost_close_only;
    int32_t signal_close_mc_bar;
    uint64_t signal_close_mc_entry_incarnation;
    uint64_t signal_close_mc_fill_seq;
    double signal_close_mc_remaining_qty;
    char comment[64];
    uint8_t comment_truncated;
    uint64_t comment_hash64;
    uint8_t requested_partial;  // deprecated, derived output only
    uint8_t full_percent_exit_request;  // deprecated, derived output only
    uint8_t pooc_global_full_exit_dynamic_qty;  // deprecated, derived output only
    uint8_t pooc_global_full_exit_tracks_bound_adds;  // deprecated, derived output only
    uint8_t pooc_global_full_exit_bound_add;  // deprecated, derived output only
    uint8_t created_while_in_position;  // deprecated, derived output only
    uint8_t sbmt_member;  // deprecated, derived output only
    double sbmt_own_qty;  // deprecated, derived output only
    double sbmt_tx_qty;  // deprecated, derived output only
    uint8_t sbmt_kept_over_cap;  // deprecated, derived output only
    double sbmt_close_qty;  // deprecated, derived output only
    uint8_t sbmt_close_buy;  // deprecated, derived output only
    uint8_t suppress_as_declined_reversal_close;
    uint8_t dormant_bracket;  // deprecated, derived output only
    uint8_t dormant_reissue_pending;  // deprecated, derived output only
    double dormant_original_stop_price;  // deprecated, derived output only
    int32_t dormant_hold_bar;  // deprecated, derived output only
    int32_t dormant_reversal_kill_bar;  // deprecated, derived output only
    double dormant_trail_best;  // deprecated, derived output only
    double dormant_trail_best_start;  // deprecated, derived output only
    uint8_t dormant_trail_leg_dead;  // deprecated, derived output only
    double suppressed_close_consumed_ledger_qty;
    double suppressed_close_retired_ledger_qty;
    int32_t short_seed_collision_role;
    uint64_t replaced_order_incarnation;
    int64_t birth_timestamp;
    int32_t birth_cause;
    int32_t birth_bar;
    int32_t birth_cursor_domain;
    int32_t birth_cursor_position;
    int32_t birth_cursor_index;
    int32_t birth_cursor_count;
    double birth_cursor_price;
    uint64_t birth_first_fill;
    uint64_t birth_last_fill;
    uint64_t birth_evaluation_ordinal;
    int32_t pine_birth_reach;
    uint64_t quantity_intent_kind;
    double quantity_intent_units;
    double quantity_intent_numerator;
    double quantity_intent_denominator;
    uint8_t quantity_reservation_present;
    double quantity_reservation_units;
    double quantity_reservation_basis_units;
    int64_t leg_activation_owner_cycle;
    uint8_t leg_activation_present;
    int64_t leg_activation_stop_first_bar;
    int64_t leg_activation_limit_first_bar;
    int64_t pine_exit_activation_owner_cycle_at_birth;
    uint8_t pine_exit_activation_present;
    int32_t pine_exit_activation_entry_bar_at_birth;
    int32_t pine_exit_activation_direction_at_birth;
    double pine_exit_activation_cursor_price_at_birth;
    double pine_exit_activation_stop_level_at_birth;
    double pine_exit_activation_limit_level_at_birth;
    uint8_t pine_exit_activation_limit_continuation_present;
    int32_t pine_exit_activation_limit_continuation_cause;
    uint64_t pine_exit_activation_limit_continuation_fill;
    int64_t reservation_expansion_position_cycle;
    uint8_t reservation_expansion_present;
    int32_t reservation_expansion_side;
    uint8_t reservation_expansion_first_later_admission_present;
    uint64_t reservation_expansion_first_later_admission;
    uint8_t reservation_growth_source_present;
    uint64_t reservation_growth_source_reservation_owner;
    uint64_t pine_frozen_market_instruction_kind;
    double pine_frozen_market_instruction_own_units;
    double pine_frozen_market_instruction_transaction_units;
    char pine_frozen_market_instruction_target_id[64];
    uint8_t pine_frozen_market_instruction_target_id_truncated;
    uint64_t pine_frozen_market_instruction_target_id_hash64;
} pf_pending_order_v1_t;

/* One row of the self-describing layout table returned by
 * strategy_pending_order_layout(): field name, C type spelling
 * ("uint8_t", "int32_t", "int64_t", "uint64_t", "double", "char[64]",
 * "uint32_t"), byte offset inside pf_pending_order_v1_t, byte size. */
typedef struct pf_field_desc_s {
    const char* name;
    const char* type;
    uint32_t offset;
    uint32_t size;
} pf_field_desc_t;
#define PF_PENDING_ORDER_STRUCT_VERSION 1
#define PF_PENDING_ORDER_STR_CAP 64
