// GENERATED by scripts/gen_pending_order_mirror.py from include/pineforge/engine.hpp -- do not edit.
#include <pineforge/engine.hpp>
#include <pineforge/pending_order_mirror.hpp>

#include <cstddef>
#include <cstring>
#include <type_traits>

static_assert(std::is_standard_layout<pf_pending_order_v1_t>::value,
              "pf_pending_order_v1_t must be standard-layout");
static_assert(std::is_trivial<pf_pending_order_v1_t>::value,
              "pf_pending_order_v1_t must be trivial (memcpy-able across the C ABI)");

namespace pineforge {
namespace {

// NUL-terminated copy of the first STR_CAP-1 bytes + FNV-1a 64 of the
// whole string, so a consumer can still match an over-long id exactly.
void copy_str(const std::string& s, char* dst, uint8_t* truncated, uint64_t* hash) {
    uint64_t h = 1469598103934665603ULL;
    for (unsigned char ch : s) { h ^= ch; h *= 1099511628211ULL; }
    *hash = h;
    const size_t n = s.size() < 63 ? s.size() : 63;
    std::memcpy(dst, s.data(), n);
    dst[n] = 0;
    *truncated = s.size() > 63 ? 1 : 0;
}

}  // namespace

void fill_pending_order_mirror(const PendingOrder& src, pf_pending_order_v1_t* out) {
    std::memset(out, 0, sizeof(*out));
    out->struct_version = 1;
    out->size = (uint32_t)sizeof(*out);
    copy_str(src.id, out->id, &out->id_truncated, &out->id_hash64);
    copy_str(src.from_entry, out->from_entry, &out->from_entry_truncated, &out->from_entry_hash64);
    out->type = (int32_t)src.type;
    out->is_long = src.is_long ? 1 : 0;
    out->limit_price = src.limit_price;
    out->stop_price = src.stop_price;
    out->trail_points = src.trail_points;
    out->trail_price = src.trail_price;
    out->trail_offset = src.trail_offset;
    out->profit_ticks = src.profit_ticks;
    out->loss_ticks = src.loss_ticks;
    out->qty = src.qty;
    out->qty_type = (int32_t)src.qty_type;
    out->qty_percent = src.qty_percent;
    copy_str(src.oca_name, out->oca_name, &out->oca_name_truncated, &out->oca_name_hash64);
    out->oca_type = (int32_t)src.oca_type;
    out->created_bar = (int32_t)src.created_bar;
    out->created_seq = src.created_seq;
    out->incarnation = src.incarnation;
    out->created_by_same_id_replacement = src.type != OrderType::RAW_ORDER && src.replaced_order_incarnation != 0 ? 1 : 0;
    out->replaced_default_market_incarnation = src.replaced_default_market_incarnation;
    out->declined_by_replaced_short_market = src.declined_by_replaced_short_market ? 1 : 0;
    out->replaced_exit_order_incarnation = src.type == OrderType::EXIT ? src.replaced_order_incarnation : 0;
    out->recreated_after_named_cancelled_entry_incarnation = src.recreated_after_named_cancelled_entry_incarnation;
    out->named_cancel_surviving_exit_incarnation = src.named_cancel_surviving_exit_incarnation;
    out->stop_limit_activated = src.stop_limit_activated ? 1 : 0;
    out->coof_suppress_stop_on_entry_bar = src.pine_exit_activation.holds_stop() ? 1 : 0;
    out->coof_suppress_limit_on_entry_bar = src.pine_exit_activation.holds_limit() ? 1 : 0;
    out->created_during_coof_recalc = src.birth.from_fill() ? 1 : 0;
    out->coof_born_at_close_recalc = src.birth.at_terminal_fill() ? 1 : 0;
    out->coof_born_mid_bar = compat::pine::historical_cascade_reach(src) ? 1 : 0;
    out->coof_cascade_seg_i = (int32_t)src.coof_cascade_seg_i;
    out->coof_cascade_inflight_fires = src.coof_cascade_inflight_fires ? 1 : 0;
    out->created_position_side = (int32_t)src.created_position_side;
    out->created_position_cycle_seq = src.created_position_cycle_seq;
    out->created_after_position_close_in_bar = src.created_after_position_close_in_bar ? 1 : 0;
    out->over_pyramiding_cap_at_placement = src.over_pyramiding_cap_at_placement ? 1 : 0;
    out->same_id_stop_deferred_close_all_bar = (int32_t)src.same_id_stop_deferred_close_all_bar;
    out->same_id_stop_deferred_close_all_incarnation = src.same_id_stop_deferred_close_all_incarnation;
    out->reverses_same_bar_market_from_flat = src.reverses_same_bar_market_from_flat ? 1 : 0;
    out->paired_flat_market_candidate = src.paired_flat_market_candidate ? 1 : 0;
    out->paired_flat_market_own_qty = src.paired_flat_market_own_qty;
    out->paired_flat_market_signal_close = src.paired_flat_market_signal_close;
    out->paired_flat_market_signal_equity = src.paired_flat_market_signal_equity;
    out->paired_flat_market_signal_margin_pct = src.paired_flat_market_signal_margin_pct;
    out->paired_flat_market_signal_pointvalue = src.paired_flat_market_signal_pointvalue;
    out->paired_flat_market_signal_fx = src.paired_flat_market_signal_fx;
    out->paired_flat_market_peer_seq = src.paired_flat_market_peer_seq;
    out->paired_flat_market_transaction_qty = src.paired_flat_market_transaction_qty;
    out->default_flat_market_gross_candidate = src.default_flat_market_gross_candidate ? 1 : 0;
    out->tv_carry_qty = src.tv_carry_qty;
    out->frozen_default_qty = src.frozen_default_qty;
    out->default_stop_placement_qty = src.default_stop_placement_qty;
    out->default_stop_placement_equity = src.default_stop_placement_equity;
    out->default_stop_placement_signal_close = src.default_stop_placement_signal_close;
    out->default_stop_sizing_price = src.default_stop_sizing_price;
    out->sizing_equity = src.sizing_equity;
    out->sizing_price = src.sizing_price;
    out->sizing_fx = src.sizing_fx;
    out->sizing_mark = src.sizing_mark;
    out->opening_affordability_exemption_candidate = src.opening_affordability_exemption_candidate ? 1 : 0;
    out->explicit_flat_admission_candidate = src.explicit_flat_admission_candidate ? 1 : 0;
    out->explicit_placement_equity = src.explicit_placement_equity;
    out->explicit_slipped_signal_close = src.explicit_slipped_signal_close;
    out->affordability_placement_equity = src.affordability_placement_equity;
    out->affordability_signal_price = src.affordability_signal_price;
    out->affordability_held_qty = src.affordability_held_qty;
    out->affordability_close_only = src.affordability_close_only ? 1 : 0;
    out->rounded_signal_cost_close_only = src.rounded_signal_cost_close_only ? 1 : 0;
    out->signal_close_mc_bar = (int32_t)src.signal_close_mc_bar;
    out->signal_close_mc_entry_incarnation = src.signal_close_mc_entry_incarnation;
    out->signal_close_mc_fill_seq = src.signal_close_mc_fill_seq;
    out->signal_close_mc_remaining_qty = src.signal_close_mc_remaining_qty;
    copy_str(src.comment, out->comment, &out->comment_truncated, &out->comment_hash64);
    out->requested_partial = src.quantity_request.is_partial(1e-9, 1e-9) ? 1 : 0;
    out->full_percent_exit_request = src.quantity_request.requests_all() ? 1 : 0;
    out->pooc_global_full_exit_dynamic_qty = src.reservation_expansion.population_open() ? 1 : 0;
    out->pooc_global_full_exit_tracks_bound_adds = src.reservation_expansion.capture().has_value() ? 1 : 0;
    out->pooc_global_full_exit_bound_add = src.reservation_growth_source.reservation_owner().has_value() ? 1 : 0;
    out->created_while_in_position = src.type == OrderType::EXIT && src.created_position_side != PositionSide::FLAT ? 1 : 0;
    out->sbmt_member = src.pine_frozen_market_instruction.active() ? 1 : 0;
    out->sbmt_own_qty = src.pine_frozen_market_instruction.transaction() ? src.pine_frozen_market_instruction.transaction()->own_units : std::numeric_limits<double>::quiet_NaN();
    out->sbmt_tx_qty = src.pine_frozen_market_instruction.transaction() ? src.pine_frozen_market_instruction.transaction()->transaction_units : std::numeric_limits<double>::quiet_NaN();
    out->sbmt_kept_over_cap = src.pine_frozen_market_instruction.transaction() && src.over_pyramiding_cap_at_placement ? 1 : 0;
    out->sbmt_close_qty = src.pine_frozen_market_instruction.targeted_close() ? src.quantity_request.intent()->units() : std::numeric_limits<double>::quiet_NaN();
    out->sbmt_close_buy = src.pine_frozen_market_instruction.targeted_close() && src.created_position_side == PositionSide::SHORT ? 1 : 0;
    out->suppress_as_declined_reversal_close = src.suppress_as_declined_reversal_close ? 1 : 0;
    out->dormant_bracket = src.dormant_bracket ? 1 : 0;
    out->dormant_reissue_pending = src.dormant_reissue_pending ? 1 : 0;
    out->dormant_original_stop_price = src.dormant_original_stop_price;
    out->dormant_hold_bar = (int32_t)src.dormant_hold_bar;
    out->dormant_reversal_kill_bar = (int32_t)src.dormant_reversal_kill_bar;
    out->dormant_trail_best = src.dormant_trail_best;
    out->dormant_trail_best_start = src.dormant_trail_best_start;
    out->dormant_trail_leg_dead = src.dormant_trail_leg_dead ? 1 : 0;
    out->suppressed_close_consumed_ledger_qty = src.suppressed_close_consumed_ledger_qty;
    out->suppressed_close_retired_ledger_qty = src.suppressed_close_retired_ledger_qty;
    out->short_seed_collision_role = (int32_t)src.short_seed_collision_role;
    out->replaced_order_incarnation = src.replaced_order_incarnation;
    out->birth_timestamp = src.birth.timestamp();
    out->birth_cause = (int32_t)src.birth.cause();
    out->birth_bar = src.birth.bar();
    out->birth_cursor_domain = (int32_t)src.birth.cursor().domain();
    out->birth_cursor_position = (int32_t)src.birth.cursor().position();
    out->birth_cursor_index = src.birth.cursor().index();
    out->birth_cursor_count = src.birth.cursor().count();
    out->birth_cursor_price = src.birth.cursor_price();
    out->birth_first_fill = src.birth.first_fill();
    out->birth_last_fill = src.birth.last_fill();
    out->birth_evaluation_ordinal = src.birth.evaluation_ordinal();
    out->pine_birth_reach = (int32_t)src.pine_birth_reach;
    out->quantity_intent_kind = src.quantity_request.intent() ? static_cast<uint64_t>(src.quantity_request.intent()->kind()) + 1 : 0;
    out->quantity_intent_units = src.quantity_request.intent() && src.quantity_request.intent()->kind() == QuantityIntent::Kind::Units ? src.quantity_request.intent()->units() : 0.0;
    out->quantity_intent_numerator = src.quantity_request.intent() && src.quantity_request.intent()->kind() == QuantityIntent::Kind::Fraction ? src.quantity_request.intent()->numerator() : 0.0;
    out->quantity_intent_denominator = src.quantity_request.intent() && src.quantity_request.intent()->kind() == QuantityIntent::Kind::Fraction ? src.quantity_request.intent()->denominator() : 0.0;
    out->quantity_reservation_present = src.quantity_request.reservation().has_value() ? 1 : 0;
    out->quantity_reservation_units = src.quantity_request.reservation() ? src.quantity_request.reservation()->units : 0.0;
    out->quantity_reservation_basis_units = src.quantity_request.reservation() ? src.quantity_request.reservation()->basis_units : 0.0;
    out->leg_activation_owner_cycle = src.leg_activation.bounds() ? src.leg_activation.bounds()->position_cycle : 0;
    out->leg_activation_present = src.leg_activation.bounds().has_value() ? 1 : 0;
    out->leg_activation_stop_first_bar = src.leg_activation.bounds() ? src.leg_activation.bounds()->stop_first_bar : 0;
    out->leg_activation_limit_first_bar = src.leg_activation.bounds() ? src.leg_activation.bounds()->limit_first_bar : 0;
    out->pine_exit_activation_owner_cycle_at_birth = src.pine_exit_activation.evidence() ? src.pine_exit_activation.evidence()->position_cycle : 0;
    out->pine_exit_activation_present = src.pine_exit_activation.evidence().has_value() ? 1 : 0;
    out->pine_exit_activation_entry_bar_at_birth = src.pine_exit_activation.evidence() ? src.pine_exit_activation.evidence()->entry_bar : 0;
    out->pine_exit_activation_direction_at_birth = src.pine_exit_activation.evidence() ? src.pine_exit_activation.evidence()->direction : 0;
    out->pine_exit_activation_cursor_price_at_birth = src.pine_exit_activation.evidence() ? src.pine_exit_activation.evidence()->cursor_price : 0.0;
    out->pine_exit_activation_stop_level_at_birth = src.pine_exit_activation.evidence() ? src.pine_exit_activation.evidence()->stop_level : 0.0;
    out->pine_exit_activation_limit_level_at_birth = src.pine_exit_activation.evidence() ? src.pine_exit_activation.evidence()->limit_level : 0.0;
    out->pine_exit_activation_limit_continuation_present = src.pine_exit_activation.evidence() && src.pine_exit_activation.evidence()->limit_continuation ? 1 : 0;
    out->pine_exit_activation_limit_continuation_cause = src.pine_exit_activation.evidence() && src.pine_exit_activation.evidence()->limit_continuation ? static_cast<int32_t>(src.pine_exit_activation.evidence()->limit_continuation->cause) : 0;
    out->pine_exit_activation_limit_continuation_fill = src.pine_exit_activation.evidence() && src.pine_exit_activation.evidence()->limit_continuation ? src.pine_exit_activation.evidence()->limit_continuation->observed_fill_sequence : 0;
    out->reservation_expansion_position_cycle = src.reservation_expansion.capture() ? src.reservation_expansion.capture()->position_cycle : 0;
    out->reservation_expansion_present = src.reservation_expansion.capture().has_value() ? 1 : 0;
    out->reservation_expansion_side = src.reservation_expansion.capture() ? static_cast<int32_t>(src.reservation_expansion.capture()->side) : 0;
    out->reservation_expansion_first_later_admission_present = src.reservation_expansion.capture() && src.reservation_expansion.capture()->first_later_admission ? 1 : 0;
    out->reservation_expansion_first_later_admission = src.reservation_expansion.capture() && src.reservation_expansion.capture()->first_later_admission ? *src.reservation_expansion.capture()->first_later_admission : 0;
    out->reservation_growth_source_present = src.reservation_growth_source.reservation_owner().has_value() ? 1 : 0;
    out->reservation_growth_source_reservation_owner = src.reservation_growth_source.reservation_owner() ? *src.reservation_growth_source.reservation_owner() : 0;
    out->pine_frozen_market_instruction_kind = static_cast<uint64_t>(src.pine_frozen_market_instruction.kind());
    out->pine_frozen_market_instruction_own_units = src.pine_frozen_market_instruction.transaction() ? src.pine_frozen_market_instruction.transaction()->own_units : 0.0;
    out->pine_frozen_market_instruction_transaction_units = src.pine_frozen_market_instruction.transaction() ? src.pine_frozen_market_instruction.transaction()->transaction_units : 0.0;
    copy_str(src.pine_frozen_market_instruction.targeted_close() ? src.pine_frozen_market_instruction.targeted_close()->target_id : std::string(), out->pine_frozen_market_instruction_target_id, &out->pine_frozen_market_instruction_target_id_truncated, &out->pine_frozen_market_instruction_target_id_hash64);
}

namespace {

#define PF_PO_FIELD(name, type) \
    { #name, type, (uint32_t)offsetof(pf_pending_order_v1_t, name), \
      (uint32_t)sizeof(((pf_pending_order_v1_t*)0)->name) }

const pf_field_desc_t kLayout[] = {
    PF_PO_FIELD(struct_version, "uint32_t"),
    PF_PO_FIELD(size, "uint32_t"),
    PF_PO_FIELD(id, "char[64]"),
    PF_PO_FIELD(id_truncated, "uint8_t"),
    PF_PO_FIELD(id_hash64, "uint64_t"),
    PF_PO_FIELD(from_entry, "char[64]"),
    PF_PO_FIELD(from_entry_truncated, "uint8_t"),
    PF_PO_FIELD(from_entry_hash64, "uint64_t"),
    PF_PO_FIELD(type, "int32_t"),
    PF_PO_FIELD(is_long, "uint8_t"),
    PF_PO_FIELD(limit_price, "double"),
    PF_PO_FIELD(stop_price, "double"),
    PF_PO_FIELD(trail_points, "double"),
    PF_PO_FIELD(trail_price, "double"),
    PF_PO_FIELD(trail_offset, "double"),
    PF_PO_FIELD(profit_ticks, "double"),
    PF_PO_FIELD(loss_ticks, "double"),
    PF_PO_FIELD(qty, "double"),
    PF_PO_FIELD(qty_type, "int32_t"),
    PF_PO_FIELD(qty_percent, "double"),
    PF_PO_FIELD(oca_name, "char[64]"),
    PF_PO_FIELD(oca_name_truncated, "uint8_t"),
    PF_PO_FIELD(oca_name_hash64, "uint64_t"),
    PF_PO_FIELD(oca_type, "int32_t"),
    PF_PO_FIELD(created_bar, "int32_t"),
    PF_PO_FIELD(created_seq, "int64_t"),
    PF_PO_FIELD(incarnation, "uint64_t"),
    PF_PO_FIELD(created_by_same_id_replacement, "uint8_t"),
    PF_PO_FIELD(replaced_default_market_incarnation, "uint64_t"),
    PF_PO_FIELD(declined_by_replaced_short_market, "uint8_t"),
    PF_PO_FIELD(replaced_exit_order_incarnation, "uint64_t"),
    PF_PO_FIELD(recreated_after_named_cancelled_entry_incarnation, "uint64_t"),
    PF_PO_FIELD(named_cancel_surviving_exit_incarnation, "uint64_t"),
    PF_PO_FIELD(stop_limit_activated, "uint8_t"),
    PF_PO_FIELD(coof_suppress_stop_on_entry_bar, "uint8_t"),
    PF_PO_FIELD(coof_suppress_limit_on_entry_bar, "uint8_t"),
    PF_PO_FIELD(created_during_coof_recalc, "uint8_t"),
    PF_PO_FIELD(coof_born_at_close_recalc, "uint8_t"),
    PF_PO_FIELD(coof_born_mid_bar, "uint8_t"),
    PF_PO_FIELD(coof_cascade_seg_i, "int32_t"),
    PF_PO_FIELD(coof_cascade_inflight_fires, "uint8_t"),
    PF_PO_FIELD(created_position_side, "int32_t"),
    PF_PO_FIELD(created_position_cycle_seq, "int64_t"),
    PF_PO_FIELD(created_after_position_close_in_bar, "uint8_t"),
    PF_PO_FIELD(over_pyramiding_cap_at_placement, "uint8_t"),
    PF_PO_FIELD(same_id_stop_deferred_close_all_bar, "int32_t"),
    PF_PO_FIELD(same_id_stop_deferred_close_all_incarnation, "uint64_t"),
    PF_PO_FIELD(reverses_same_bar_market_from_flat, "uint8_t"),
    PF_PO_FIELD(paired_flat_market_candidate, "uint8_t"),
    PF_PO_FIELD(paired_flat_market_own_qty, "double"),
    PF_PO_FIELD(paired_flat_market_signal_close, "double"),
    PF_PO_FIELD(paired_flat_market_signal_equity, "double"),
    PF_PO_FIELD(paired_flat_market_signal_margin_pct, "double"),
    PF_PO_FIELD(paired_flat_market_signal_pointvalue, "double"),
    PF_PO_FIELD(paired_flat_market_signal_fx, "double"),
    PF_PO_FIELD(paired_flat_market_peer_seq, "int64_t"),
    PF_PO_FIELD(paired_flat_market_transaction_qty, "double"),
    PF_PO_FIELD(default_flat_market_gross_candidate, "uint8_t"),
    PF_PO_FIELD(tv_carry_qty, "double"),
    PF_PO_FIELD(frozen_default_qty, "double"),
    PF_PO_FIELD(default_stop_placement_qty, "double"),
    PF_PO_FIELD(default_stop_placement_equity, "double"),
    PF_PO_FIELD(default_stop_placement_signal_close, "double"),
    PF_PO_FIELD(default_stop_sizing_price, "double"),
    PF_PO_FIELD(sizing_equity, "double"),
    PF_PO_FIELD(sizing_price, "double"),
    PF_PO_FIELD(sizing_fx, "double"),
    PF_PO_FIELD(sizing_mark, "double"),
    PF_PO_FIELD(opening_affordability_exemption_candidate, "uint8_t"),
    PF_PO_FIELD(explicit_flat_admission_candidate, "uint8_t"),
    PF_PO_FIELD(explicit_placement_equity, "double"),
    PF_PO_FIELD(explicit_slipped_signal_close, "double"),
    PF_PO_FIELD(affordability_placement_equity, "double"),
    PF_PO_FIELD(affordability_signal_price, "double"),
    PF_PO_FIELD(affordability_held_qty, "double"),
    PF_PO_FIELD(affordability_close_only, "uint8_t"),
    PF_PO_FIELD(rounded_signal_cost_close_only, "uint8_t"),
    PF_PO_FIELD(signal_close_mc_bar, "int32_t"),
    PF_PO_FIELD(signal_close_mc_entry_incarnation, "uint64_t"),
    PF_PO_FIELD(signal_close_mc_fill_seq, "uint64_t"),
    PF_PO_FIELD(signal_close_mc_remaining_qty, "double"),
    PF_PO_FIELD(comment, "char[64]"),
    PF_PO_FIELD(comment_truncated, "uint8_t"),
    PF_PO_FIELD(comment_hash64, "uint64_t"),
    PF_PO_FIELD(requested_partial, "uint8_t"),
    PF_PO_FIELD(full_percent_exit_request, "uint8_t"),
    PF_PO_FIELD(pooc_global_full_exit_dynamic_qty, "uint8_t"),
    PF_PO_FIELD(pooc_global_full_exit_tracks_bound_adds, "uint8_t"),
    PF_PO_FIELD(pooc_global_full_exit_bound_add, "uint8_t"),
    PF_PO_FIELD(created_while_in_position, "uint8_t"),
    PF_PO_FIELD(sbmt_member, "uint8_t"),
    PF_PO_FIELD(sbmt_own_qty, "double"),
    PF_PO_FIELD(sbmt_tx_qty, "double"),
    PF_PO_FIELD(sbmt_kept_over_cap, "uint8_t"),
    PF_PO_FIELD(sbmt_close_qty, "double"),
    PF_PO_FIELD(sbmt_close_buy, "uint8_t"),
    PF_PO_FIELD(suppress_as_declined_reversal_close, "uint8_t"),
    PF_PO_FIELD(dormant_bracket, "uint8_t"),
    PF_PO_FIELD(dormant_reissue_pending, "uint8_t"),
    PF_PO_FIELD(dormant_original_stop_price, "double"),
    PF_PO_FIELD(dormant_hold_bar, "int32_t"),
    PF_PO_FIELD(dormant_reversal_kill_bar, "int32_t"),
    PF_PO_FIELD(dormant_trail_best, "double"),
    PF_PO_FIELD(dormant_trail_best_start, "double"),
    PF_PO_FIELD(dormant_trail_leg_dead, "uint8_t"),
    PF_PO_FIELD(suppressed_close_consumed_ledger_qty, "double"),
    PF_PO_FIELD(suppressed_close_retired_ledger_qty, "double"),
    PF_PO_FIELD(short_seed_collision_role, "int32_t"),
    PF_PO_FIELD(replaced_order_incarnation, "uint64_t"),
    PF_PO_FIELD(birth_timestamp, "int64_t"),
    PF_PO_FIELD(birth_cause, "int32_t"),
    PF_PO_FIELD(birth_bar, "int32_t"),
    PF_PO_FIELD(birth_cursor_domain, "int32_t"),
    PF_PO_FIELD(birth_cursor_position, "int32_t"),
    PF_PO_FIELD(birth_cursor_index, "int32_t"),
    PF_PO_FIELD(birth_cursor_count, "int32_t"),
    PF_PO_FIELD(birth_cursor_price, "double"),
    PF_PO_FIELD(birth_first_fill, "uint64_t"),
    PF_PO_FIELD(birth_last_fill, "uint64_t"),
    PF_PO_FIELD(birth_evaluation_ordinal, "uint64_t"),
    PF_PO_FIELD(pine_birth_reach, "int32_t"),
    PF_PO_FIELD(quantity_intent_kind, "uint64_t"),
    PF_PO_FIELD(quantity_intent_units, "double"),
    PF_PO_FIELD(quantity_intent_numerator, "double"),
    PF_PO_FIELD(quantity_intent_denominator, "double"),
    PF_PO_FIELD(quantity_reservation_present, "uint8_t"),
    PF_PO_FIELD(quantity_reservation_units, "double"),
    PF_PO_FIELD(quantity_reservation_basis_units, "double"),
    PF_PO_FIELD(leg_activation_owner_cycle, "int64_t"),
    PF_PO_FIELD(leg_activation_present, "uint8_t"),
    PF_PO_FIELD(leg_activation_stop_first_bar, "int64_t"),
    PF_PO_FIELD(leg_activation_limit_first_bar, "int64_t"),
    PF_PO_FIELD(pine_exit_activation_owner_cycle_at_birth, "int64_t"),
    PF_PO_FIELD(pine_exit_activation_present, "uint8_t"),
    PF_PO_FIELD(pine_exit_activation_entry_bar_at_birth, "int32_t"),
    PF_PO_FIELD(pine_exit_activation_direction_at_birth, "int32_t"),
    PF_PO_FIELD(pine_exit_activation_cursor_price_at_birth, "double"),
    PF_PO_FIELD(pine_exit_activation_stop_level_at_birth, "double"),
    PF_PO_FIELD(pine_exit_activation_limit_level_at_birth, "double"),
    PF_PO_FIELD(pine_exit_activation_limit_continuation_present, "uint8_t"),
    PF_PO_FIELD(pine_exit_activation_limit_continuation_cause, "int32_t"),
    PF_PO_FIELD(pine_exit_activation_limit_continuation_fill, "uint64_t"),
    PF_PO_FIELD(reservation_expansion_position_cycle, "int64_t"),
    PF_PO_FIELD(reservation_expansion_present, "uint8_t"),
    PF_PO_FIELD(reservation_expansion_side, "int32_t"),
    PF_PO_FIELD(reservation_expansion_first_later_admission_present, "uint8_t"),
    PF_PO_FIELD(reservation_expansion_first_later_admission, "uint64_t"),
    PF_PO_FIELD(reservation_growth_source_present, "uint8_t"),
    PF_PO_FIELD(reservation_growth_source_reservation_owner, "uint64_t"),
    PF_PO_FIELD(pine_frozen_market_instruction_kind, "uint64_t"),
    PF_PO_FIELD(pine_frozen_market_instruction_own_units, "double"),
    PF_PO_FIELD(pine_frozen_market_instruction_transaction_units, "double"),
    PF_PO_FIELD(pine_frozen_market_instruction_target_id, "char[64]"),
    PF_PO_FIELD(pine_frozen_market_instruction_target_id_truncated, "uint8_t"),
    PF_PO_FIELD(pine_frozen_market_instruction_target_id_hash64, "uint64_t"),
};

#undef PF_PO_FIELD

}  // namespace

const pf_field_desc_t* pending_order_layout(int* count) {
    if (count) *count = (int)(sizeof(kLayout) / sizeof(kLayout[0]));
    return kLayout;
}

}  // namespace pineforge
